pactumjs/pactum

- package-lock.json
- package.json
- src/exports/provider.js
- src/helpers/colors.js
- src/helpers/logger.js
* Removed colors npm pkg dependency
* Custom color helper
* Updated logger to use custom color helper
> Removed colors npm pkg dependency

- src/models/Spec.d.ts
- src/models/Spec.js
- src/models/expect.js
- test/component/expects.spec.js
- expectJsonMatchStrict
- expectJsonMatchStrictAt
> added expectJsonMatchStrict assertions

- src/exports/expect.d.ts
- src/exports/expect.js
- src/models/Spec.d.ts
- src/models/Spec.js
- src/models/Tosser.js
- src/models/expect.js
- test/component/bdd.spec.js
- test/component/expects.spec.js
> added expect Error

- README.md
- package-lock.json
- package.json
- src/exports/request.d.ts
- src/exports/request.js
- src/helpers/requestProcessor.js
> url bug fix

- src/models/State.js
> fix add empty line and removed an one empty one

- package-lock.json
- package.json
- src/exports/mock.d.ts
- src/exports/reporter.d.ts
- src/helpers/utils.js
- src/models/Interaction.model.js
- src/models/Spec.d.ts
- src/models/Spec.js
- src/models/Tosser.js
- test/component/form.spec.js
- test/component/save.spec.js
> 164 save files from response to fs

- package-lock.json
- package.json
- src/exports/mock.d.ts
- src/helpers/requestProcessor.js
- src/models/Interaction.model.js
- src/models/server.js
- test/component/files.spec.js
- test/component/interactions.file.spec.js
- test/component/interactions.mock.spec.js
- test/component/interactions.spec.js
> 176 mock files

- package-lock.json
- package.json
- src/helpers/toss.helper.js
- src/models/Spec.d.ts
- src/models/Spec.js
- src/models/Tosser.js
- test/component/inspect.spec.js
> feat: inspect custom parts of req and res

- package-lock.json
- package.json
- src/helpers/requestProcessor.js
- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/base.spec.js
- test/component/form.multi-part.spec.js
- test/component/form.spec.js
- test/unit/spec.spec.js
> feat: support data templates in form data

- README.md
hi @ASaiAnudeep 
I've tried to implement CLI tool to install & generate PactumJS test example called [pactum-init](https://github.com/depapp/pactum-init) - similar to this PR https://github.com/pactumjs/pactum-cucumber-boilerplate/pull/5#issue-1352021434
hope this can help people out there to use PactumJS 🙏🏻 
please let me know if I miss anything 🙇🏻
> docs: add pactum-init installation

- package-lock.json
- package.json
- src/helpers/dataProcessor.js
- test/unit/dataProcessor.spec.js
> fix: use data management in data function handlers

- .github/ISSUE_TEMPLATE/bug_report.md
- package-lock.json
- package.json
- src/exports/expect.d.ts
- src/exports/expect.js
- src/models/Spec.d.ts
- src/models/Spec.js
- src/models/expect.js
- test/component/expect.jsonSnapshot.spec.js
- test/component/expects.spec.js
> feat: expect json snapshot in bdd

- package-lock.json
- package.json
- src/exports/mock.d.ts
- src/exports/reporter.d.ts
> fix: typescript definitions for mock and reporter

- package-lock.json
- package.json
- src/helpers/dataProcessor.js
- test/unit/dataProcessor.spec.js
- test/unit/parse.spec.js
> 233 read environment variables via data management

- src/helpers/helper.js
- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/withQueryParams.spec.js
- test/unit/spec.spec.js
> feat: support query params without values

- package-lock.json
- package.json
- src/helpers/helper.js
- src/models/Spec.js
- test/component/withQueryParams.spec.js
> feat: support duplicate query params

- package-lock.json
- package.json
- src/exports/handler.d.ts
- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/withCompression.spec.js
- test/data/files/convert.js
- test/data/files/data.txt.br
> feat: compression request option

- package-lock.json
- package.json
- src/exports/mock.d.ts
- src/exports/mock.js
- test/unit/interaction.spec.js
> interaction type def

- src/helpers/toss.helper.js
- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/stores.spec.js
the issue link: https://github.com/pactumjs/pactum/issues/274
> Feat store with custom function

- src/models/Spec.d.ts
update types of stores
link issue: https://github.com/pactumjs/pactum/issues/274
> feat: update types of stores

- src/exports/mock.d.ts
With a bit of a delay as I was working on another project – here the changes as discussed in https://github.com/pactumjs/pactum/issues/270#issuecomment-1489914916
I tested them locally with my project, all tests run through. I ran the `npm run lint` command manually, as `eslint` doesn’t seem to be a dependency of the project. There were some eslint errors appearing which are unrelated to my changes, I assume this is a known issue?
Thanks for your support!
> 270: improve TS definitions to be able to index body of interaction

- src/exports/expect.js
- src/helpers/file.utils.js
- test/component/expects.custom.spec.js
- test/component/withJson.spec.js
> fix: error printing and withJson invalid file

- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/templates.spec.js
- test/component/withJson.spec.js
> feat: support data template name in withJson and expectJson

- src/helpers/memo.js
- src/index.d.ts
- src/index.js
- src/models/Spec.js
- test/component/memo.spec.js
> feat: memo spec handlers

- package.json
**Summary**
- Bump version to 3.6.7
> Bump version to 3.6.7

- src/exports/expect.d.ts
- src/exports/expect.js
- src/models/Spec.d.ts
- src/models/Spec.js
- src/models/expect.js
- test/component/expects.spec.js
closes https://github.com/pactumjs/pactum/issues/308
> feat: message param for expectStatus
