pactumjs/pactum

- src/models/Interaction.model.js
- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/request.spec.js
Support for OPTIONS and TRACE request-methods added.
Also, withPath and withMethod methods have been added.
(a) Files Updated :
- models/spec.js
- models/spec.d.ts
(b) Methods implemented in spec.js:
- options(url)
- trace(url)
- withPath(url)
- withMethod(method)
(c) Tests added in request.spec.js
(d) Interaction.model.js 
- "OPTIONS" and "TRACE" added in ALLOWED_REQUEST_METHODS
> #47 support | add trace and options request-methods

- src/config.js
- src/exports/response.d.ts
- src/exports/response.js
- src/helpers/errors.js
- src/helpers/utils.js
- src/index.d.ts
- src/index.js
- src/models/Spec.js
- src/models/expect.js
- test/component/response.spec.js
- test/unit/response.spec.js
Closes #55 
Support for Global Expectations on responses.
**Feature Implemented**
Supports global response expectations for response - headers, status and response time.
- pactum.response
- setDefaultExpectResponseTime()
- setDefaultExpectStatus()
- setDefaultExpectHeader()
**Change log:**
- Files updated:
- src/config.js
- src/helpers/errors.js
- src/helpers/utils.js
- src/index.d.ts
- src/index.js
- src/models/Spec.js
- src/models/expect.js
- Files added:
- src/exports/response.d.ts
- src/exports/response.js
- test/unit/response.spec.js
- src/exports/response.d.ts
Documentation updated: https://github.com/pactumjs/pactumjs.github.io/pull/2
Cheer!
Prasad
> Support global response default expectations

- package-lock.json
- package.json
- src/exports/mock.d.ts
- src/models/Interaction.model.js
- src/models/expect.js
- test/component/interactions.spec.js
- test/component/remote.server.spec.js
- test/component/remote.spec.js
- test/unit/interaction.spec.js
Closes #105 
Changes:
- Added a new property to the interaction object
```js
exceptions: {
checkExercised: true    // default
}
```
- Works with `interaction handlers`, `useInteraction`, `addInteraction`
- Unit & Component test update.
- Bump `pactum-matchers` version to `1.0.6`
- Bump `pactum` version to `3.1.2`
> Supoprt skip interaction exercised in exceptions

- src/config.js
- src/exports/mock.d.ts
- src/exports/mock.js
- src/models/server.js
- test/unit/mock.spec.js
**Changes:**
This PR adds additional support to the request: https://github.com/pactumjs/pactum/issues/119
_Enhancement:_
- Update console log when mock server starts to include address and port (ex: http://127.0.0.1:3000)
- `[I] Mock server is listening on http://127.0.0.1:3000`
- Add support to set mock server's host address (defaults to `0.0.0.0` to listen on all interfaces)
Usage:
```js
mock.start()                       // Runs on all interfaces & port :9393
mock.start(3000)                   // Runs on all interfaces & port :3000 
mock.start(3000, '127.0.0.1')    // Runs on 127.0.0.1:3000 or localhost:3000
```
> Add support for setting mock server host address

- src/index.d.ts
- src/models/Step.d.ts
The `spec` methods can now be used with generics to add better type support for the `data` parameter. Now instead of being typed as `any`, the default is still `any`, but a developer can do `spec<SomeInterface>('spec name', objectThatAdheresToSomeInterface)` and get Typescript support if the passed data is incorrect in any way
> feat: add generics support for specs

- src/exports/mock.d.ts
Fixes #162
I used the type object to use the same as another object types.
> fix: GraphQLRequest variables type

- src/exports/expect.d.ts
In the file `src/models/Spec.d.ts` there is an import:
```
import { Expect } from '../exports/expect';
```
However `src/exports/expect.d.ts` doesn't have a _named_ export called
`Expect` because it's not imported. This should fix that.
Also: I noticed that the default export function in the JS code takes an extra parameter called `spec`, so I added those as well with a rather broad `any` type though.
--
I would like to have this fixed because it fails the linting rules at the moment:
```typescript
this.lastRequest.response().should.have.status(201);
```
Where `this.lastRequest` is a `Spec`. So `this.lastRequest.response()` gives an `Expect`, but it doesn't really know what type it is because of the wrong type definitions. Therefore the linter fails with the fact that `should` is called on …
> Fix type definitions for expect.d.ts

- src/models/Spec.d.ts
Reading through the sources it seems to me that `Spec#returns(...)` will
either return something directly or (if the response is not yet there)
it will continue building the spec. This is not shown in the type
definitions.
In this way you can use it like this if you already have a response.
```
const x  = spec.returns<number>('res.body') // number
```
But will continue the spec if you don't give a type argument:
```
const x = spec.returns('res.body') // Spec
```
> Fix type defitions for Spec#returns

- src/models/Spec.d.ts
This PR intends to resolve this issue: https://github.com/pactumjs/pactum/issues/199
> fix: provide type definition for Spec.then method

- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/withBearerToken.spec.js
- test/unit/spec.spec.js
add withBearerToken method to Spec to set the bearer token in the request
- Before
```javascript
// ...
await spec
.get('/')
.withHeaders("Authorization", `Bearer ${token}`)
// ...
```
- After
```javascript
// ...
await spec
.get('/')
.withBearerToken(token)
// ...
```
> feat(src/models/Spec.js): add withBearerToken method

- src/exports/mock.d.ts
- src/helpers/toss.helper.js
- src/models/Interaction.model.js
- test/component/returns.spec.js
- test/component/stores.spec.js
closes #174.
In addition, you can now add `cookies` to the interaction request and response:
```js
mock.addInteraction({
request: {
method: 'GET',
path: '/api/hello',
cookies: {
lang: 'en',
}
},
response: {
status: 200,
body: 'Hello, 👋',
cookies: {
token: 'xyz',
}
}
});
```
> feat: capture cookies with res.cookies and req.cookies in stores and returns

- package-lock.json
- package.json
- src/models/Spec.d.ts
- src/models/expect.js
- test/component/expects.spec.js
closes #290 
Support pactum matchers in `expectJsonLength` assertion.
**Changes:**
- Allow `pactum-matchers` on `expectJsonLength`
- allowed matchers - `gte, lte, lt, gt. notEquals`
- `semver` vulnerability fix - updated via `npm audit fix`
- Bump version to `3.5.1`
**Examples**
```js
const { spec } = require('pactum');
const { gte, lte, lt, gt } = require("pactum-matchers");
await spec()
.get('https://reqres.in/api/users')
.expectJsonLength('data', lte(6));
```
```js
const { spec } = require('pactum');
const { gte, lte, lt, gt } = require("pactum-matchers");
await spec()
.get('https://jsonplaceholder.typicode.com/users')
.expectJsonLength('.', gte(10));
```
> feat: expectjsonlength enhancement

- src/helpers/dataProcessor.js
- test/unit/dataProcessor.spec.js
Reference issue: #305 
When providing parameters to function mapping (ie: `$F{sum:1,2}`), if the parameter includes a : character, the rest of the parameter is cut off from being included in the arguments.
In dataProcessor.js line 104, the `FunctionName:param1,param2` string is being split up by the : character for all instances of the character, causing arguments which include a : to be split and not passed to the function when it is filtered out on line 106.
I modified the behavior by changing the `refValue.split(':')` on line 104 to use a regex expression to only split by the first instance of the : character like so `refValue.split(/:(.*)/)` so params including the ':' character can be passed to functions
> Modified data processor functional param splitting logic

- package-lock.json
- package.json
- src/exports/mock.d.ts
- src/exports/reporter.d.ts
- tsconfig.json
I discovered an issue where the types on the `ExercisedInteraction` interface didn't match the `Interaction` interface it extends. See the issue below when running `tsc`. I've resolved this by creating a few super class interfaces with more broad types, but the child classes have more defined types.
```
> tsc
src/exports/reporter.d.ts:23:18 - error TS2430: Interface 'ExercisedInteraction' incorrectly extends interface 'Interaction'.
Types of property 'calls' are incompatible.
Type 'import("C:/Users/dansc/projects/pactum/src/exports/reporter").InteractionCall[]' is not assignable to type 'import("C:/Users/dansc/projects/pactum/src/exports/mock").InteractionCall[]'.
Type 'import("C:/Users/dansc/projects/pactum/src/exports/reporter").InteractionCall' is not assignable to type …
```
> Fix reporter and mock types

- package-lock.json
- package.json
- src/adapters/json.like.js
- src/models/expect.js
- test/unit/json.like.spec.js
> feat: added root_path to jsonLike

- src/models/Spec.js
- test/component/interactions.spec.js
**Summary**
- Closes #344 
- withCore method was overriding the core options of request object, fix is to extend/override using `deep-override` instead of direct assignment.
- After this fix`withCore` and `withAuth` sequence in chaining can be shuffled.
> Note: if `withCore` is used at the end of the request chaining, options in `withCore` (if provided) will override in http request.
> Fix withCore overriding request core options when using withAuth

- package-lock.json
- package.json
- src/models/Spec.d.ts
- src/models/Spec.js
- src/models/Tosser.js
- test/component/bdd.spec.js
- test/component/spec.handler.spec.js
Enhancement for the below issue:
https://github.com/pactumjs/pactum/issues/349
Hi @ASaiAnudeep ,
Could you pls review this PR
> Sleep after running a spec

- package-lock.json
- package.json
- src/exports/request.d.ts
- src/exports/request.js
- test/unit/request.spec.js
Hi @ASaiAnudeep , the following changes are for Issue #365
Done the following:
1. Have merged removeDefaultHeader and removeDefaultHeaders into one method removeDefaultHeaders
2. If key is mentioned it will delete the particular default header else if nothing is mentioned will delete all the default 
headers
3. Have removed one unit test due to the current changes, as now based on the truthiness of the key we are deciding what 
action to be performed
4. Have added 2 unit tests
5. Added the doc for removeDefaultHeaders, PR link - https://github.com/pactumjs/pactumjs.github.io/pull/52
Please review the changes and do the needful. Thanks!
> Merged removeDefaultHeader and removeDefaultHeaders methods into one

- package-lock.json
- package.json
- src/config.js
- src/exports/request.d.ts
- src/exports/request.js
- src/helpers/requestProcessor.js
- src/models/Spec.d.ts
- src/models/Spec.js
- test/component/interactions.mock.spec.js
closes #372 
**Change Summary:**
* Allow withFollowRedirects and setDefaultFollowRedirects to support boolean and number parameters.
* Allow setting the followRedirects at 
* request level `withFollowRedirects` 
* global `setDefaultFollowRedirects` level.
* Default redirects should be `20` and should `>=0`
* Allow users to increase or decrease the redirect count
PR for documentation update - https://github.com/pactumjs/pactumjs.github.io/pull/55
> Allow configuring follow redirects count

- src/exports/mock.d.ts
- test/component/expects.spec.js
- test/component/non.crud.spec.js
- test/component/response.spec.js
closes #381
Includes fixes for test failures with node v20.18.1 changes (https://github.com/nodejs/node/pull/54759) 
Node v20.18.1 has changes to assert: https://nodejs.org/en/blog/release/v20.18.1
> fix: Mock interaction type definitions

- src/models/expect.js
closes #287 
- When an `actualCookie` is an array with multiple elements, they are joined with `'; '` to make a single string before parsing.
- It is OK without it, but adding `';'` after all `join()` operations are complete ensures that the state before parsing multiple cookies is the same as a single string cookie.
Example: 
If an array of cookies like `["one=1", "two=2"]` is set via `set-cookie` header, the `join()` operation will result in a string like `'one=1; two=2;'` which can be parsed correctly.
> Bugfix: Ensure array-style 'set-cookie' headers are parsed correctly

- package-lock.json
- package.json
- src/helpers/toss.helper.js
- src/helpers/utils.js
- src/models/Interaction.model.js
- src/models/Spec.js
- src/models/expect.js
**Summary**
- closes #396 
- Replaced [lightcookie](https://www.npmjs.com/package/lightcookie) with [cookie-lite](https://www.npmjs.com/package/cookie-lite) post `lightcookie` deprecation. Details [here](https://github.com/ethan7g/lightcookie/issues/3)
- `npm audit fix` for below
> chore: replace lightcookie with cookie-lite
